github action added

diff --git a/TmkMordorGate/.github/actions/tmk-build-and-push.yaml b/TmkMordorGate/.github/actions/tmk-build-and-push.yaml
--- a/TmkMordorGate/.github/actions/tmk-build-and-push.yaml
+++ b/TmkMordorGate/.github/actions/tmk-build-and-push.yaml
@@ -4,11 +4,81 @@ on:
   push:
     branches:
       - main
+  workflow_dispatch:
+    inputs:
+      branch:
+        description: "Branch to build from"
+        required: true
+      tag:
+        description: "Tag to build"
+        required: true
 
 jobs:
-  print-message:
+  build-and-push:
     runs-on: ubuntu-latest
-
+    environment: staging
     steps:
-      - name: Print Hello World
-        run: echo "Hello, World!"
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.branch || github.ref }}
+
+      - name: Validate tag version
+        id: check-condition
+        run: |
+          echo "Ref: $GITHUB_REF"
+          # Assuming GITHUB_REF could be a tag based on the event
+          if [[ "$GITHUB_REF" =~ refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
+            echo "Valid semantic version tag"
+            echo "proceed=true" >> $GITHUB_ENV
+          else
+            echo "Invalid or no semantic version tag"
+            echo "proceed=true" >> $GITHUB_ENV
+          fi
+
+      - name: Extract image tag
+        if: env.proceed == 'true'
+        run: |
+          if [[ "$GITHUB_REF" =~ ^refs/tags/(.+)$ ]]; then
+            TAG=${BASH_REMATCH[1]}
+            echo "Extracted tag: $TAG"
+          else
+            TAG=${GITHUB_SHA}  # Fallback to commit SHA if not a tag
+            echo "Using commit SHA as tag because no version tag is present: $TAG"
+          fi
+          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
+          echo "${{ github.ref }}" > tmk_face_latest_image_tag.txt
+
+      - name: Bridge workflow
+        if: env.proceed == 'false'
+        run: |
+          echo "Skipping the workflow"
+          exit 1
+
+      - name: Set up QEMU
+        if: env.proceed == 'true'
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        if: env.proceed == 'true'
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to DockerHub
+
+      - name: Build and push multi-arch image
+        if: env.proceed == 'true'
+        uses: docker/build-push-action@v5
+        with:
+        context: .
+        file: Dockerfile
+        platforms: linux/amd64,linux/arm64  # Specify the platforms
+        push: true
+        build-args: |
+          VITE_TMK_GATEWAY_URL=${{ secrets.VITE_TMK_GATEWAY_URL }}
+        tags: |
+          marcoguerod/tmkface-amd64:${{ github.event.inputs.tag || env.IMAGE_TAG }}
+          marcoguerod/tmkface-arm64:${{ github.event.inputs.tag || env.IMAGE_TAG }}
+      
+      - name: Logout from Docker
+        if: steps.check-condition.outputs.proceed == 'true'
+        run: docker logout
