adjust dockerfile

diff --git a/.github/workflows/tmk-build-and-push.yaml b/.github/workflows/tmk-build-and-push.yaml
--- a/.github/workflows/tmk-build-and-push.yaml
+++ b/.github/workflows/tmk-build-and-push.yaml
@@ -1,16 +1,16 @@
-name: Build and Push Docker image
+name: Build and Push Docker image to DockerHub
 
 on:
   push:
     tags:
-      - 'v*'  # Push events to matching v*, i.e. v1.0.0, v20.15.10
+      - "v*" # Push events to matching v*, i.e. v1.0.0, v20.15.10
   workflow_dispatch:
     inputs:
       branch:
-        description: 'Branch to build from'
+        description: "Branch to build from"
         required: true
       tag:
-        description: 'Tag to build'
+        description: "Tag to build"
         required: true
 
 jobs:
@@ -18,73 +18,73 @@ jobs:
     runs-on: ubuntu-latest
     environment: staging
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-      with:
-        ref: ${{ github.event.inputs.branch || github.ref }}
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.branch || github.ref }}
 
-    - name: List files in TmkMordorGate
-      run: ls -l ./TmkMordorGate/
+      - name: List files in TmkMordorGate
+        run: ls -l ./TmkMordorGate/
 
-    - name: Validate tag version
-      id: check-condition
-      run: |
-        echo "Ref: $GITHUB_REF"
-        # Assuming GITHUB_REF could be a tag based on the event
-        if [[ "$GITHUB_REF" =~ refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
-          echo "Valid semantic version tag"
-          echo "proceed=true" >> $GITHUB_ENV
-        else
-          echo "Invalid or no semantic version tag"
-          echo "proceed=true" >> $GITHUB_ENV
-        fi
-    
-    - name: Extract image tag
-      if: env.proceed == 'true'
-      run:  |
-        if [[ "$GITHUB_REF" =~ ^refs/tags/(.+)$ ]]; then
-          TAG=${BASH_REMATCH[1]}
-          echo "Extracted tag: $TAG"
-        else
-          TAG=${GITHUB_SHA}  # Fallback to commit SHA if not a tag
-          echo "Using commit SHA as tag because no version tag is present: $TAG"
-        fi
-        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
-        echo "${{ github.ref }}" > tmk_mordor_gate_latest_image_tag.txt
+      - name: Validate tag version
+        id: check-condition
+        run: |
+          echo "Ref: $GITHUB_REF"
+          # Assuming GITHUB_REF could be a tag based on the event
+          if [[ "$GITHUB_REF" =~ refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
+            echo "Valid semantic version tag"
+            echo "proceed=true" >> $GITHUB_ENV
+          else
+            echo "Invalid or no semantic version tag"
+            echo "proceed=true" >> $GITHUB_ENV
+          fi
 
-    - name: Bridge workflow
-      if: env.proceed == 'false'
-      run:  |
-        echo "Skipping the workflow"
-        exit 1
+      - name: Extract image tag
+        if: env.proceed == 'true'
+        run: |
+          if [[ "$GITHUB_REF" =~ ^refs/tags/(.+)$ ]]; then
+            TAG=${BASH_REMATCH[1]}
+            echo "Extracted tag: $TAG"
+          else
+            TAG=${GITHUB_SHA}  # Fallback to commit SHA if not a tag
+            echo "Using commit SHA as tag because no version tag is present: $TAG"
+          fi
+          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
+          echo "${{ github.ref }}" > tmk_mordor_gate_latest_image_tag.txt
 
-    - name: Set up QEMU
-      if: env.proceed == 'true'
-      uses: docker/setup-qemu-action@v3
+      - name: Bridge workflow
+        if: env.proceed == 'false'
+        run: |
+          echo "Skipping the workflow"
+          exit 1
 
-    - name: Set up Docker Buildx
-      if: env.proceed == 'true'
-      uses: docker/setup-buildx-action@v3
+      - name: Set up QEMU
+        if: env.proceed == 'true'
+        uses: docker/setup-qemu-action@v3
 
-    - name: Login to DockerHub
-      if: env.proceed == 'true'
-      uses: docker/login-action@v3
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Set up Docker Buildx
+        if: env.proceed == 'true'
+        uses: docker/setup-buildx-action@v3
 
-    - name: Build and push multi-arch image
-      if: env.proceed == 'true'
-      uses: docker/build-push-action@v5
-      with:
-        context: ./TmkMordorGate/
-        file: Dockerfile
-        platforms: linux/amd64,linux/arm64  # Specify the platforms
-        push: true
-        tags: |
-          marcoguerod/tmkmordorgate-amd64:${{ github.event.inputs.tag || env.IMAGE_TAG }}
-          marcoguerod/tmkmordorgate-arm64:${{ github.event.inputs.tag || env.IMAGE_TAG }}
+      - name: Login to DockerHub
+        if: env.proceed == 'true'
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Logout from Docker
-      if: steps.check-condition.outputs.proceed == 'true'
-      run: docker logout
+      - name: Build and push multi-arch image
+        if: env.proceed == 'true'
+        uses: docker/build-push-action@v5
+        with:
+          context: ./TmkMordorGate/
+          file: Dockerfile
+          platforms: linux/amd64,linux/arm64 # Specify the platforms
+          push: true
+          tags: |
+            marcoguerod/tmkmordorgate-amd64:${{ github.event.inputs.tag || env.IMAGE_TAG }}
+            marcoguerod/tmkmordorgate-arm64:${{ github.event.inputs.tag || env.IMAGE_TAG }}
+
+      - name: Logout from Docker
+        if: steps.check-condition.outputs.proceed == 'true'
+        run: docker logout
